[package]
name = "vim-navigation"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vim_navigation"
path = "vim_navigation.rs"

[dependencies]
rdev = { path = "../rdev", features = ["unstable_grab"] }
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"