initial_move_step = 0.0005
acceleration_base = 1.0
acceleration_multiplier = 30.0
repeat_delay_ms = 20
move_delay_ms = 15
precision_divisor = 100.0

# Navigation keys
key_left = "h"
key_down = "j"
key_up = "k"
key_right = "l"

# Control keys
key_click = "return"
key_toggle_mode = "command+shift+s"
key_right_click = "i"
key_select_toggle = "v"
key_goto_top = "g"
key_goto_bottom = "shift_g"
key_yank = "y"
key_paste = "p"
